services:
  register:
    image: oven/bun:latest
    command: sh -c "cd /app && (bun install || true) && cd apps/register && bunx prisma generate && bun run dev"
    working_dir: /app/apps/register
    container_name: projeto-3-register
    volumes:
      - .:/app
      - register_modules:/app/node_modules
    environment:
      NEON_DATABASE_URL: ${NEON_DATABASE_URL_REGISTER}
      PORT: 3000
      CORS_ORIGIN: https://clinicasdigitais.cin.ufpe.br
      NODE_ENV: development
    restart: on-failure
    ports:
      - "3010:3000"
    networks:
      - cin_proxy

  auth:
    image: oven/bun:latest
    command: sh -c "cd /app && (bun install || true) && cd apps/auth && bunx prisma generate && bun run dev"
    working_dir: /app/apps/auth
    container_name: projeto-3-auth
    volumes:
      - .:/app
      - auth_modules:/app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL_AUTH}
      DATABASE_URL_POOLED: ${DATABASE_URL_AUTH}
      JWT_SECRET: ${JWT_SECRET}
      REGISTER_SERVICE_URL: http://projeto-3-register:3000
      PORT: 3001
      CORS_ORIGIN: https://clinicasdigitais.cin.ufpe.br
      NODE_ENV: development
    depends_on:
      - register
    ports:
      - "3011:3001"
    restart: on-failure
    networks:
      - cin_proxy

  historico:
    image: oven/bun:latest
    container_name: projeto-3-historico
    command: sh -c "cd /app && (bun install || true) && cd apps/historico && bunx prisma generate && bun run dev"
    working_dir: /app/apps/historico
    volumes:
      - .:/app
      - historico_modules:/app/node_modules
    environment:
      NEON_DATABASE_URL_DEV: ${NEON_DATABASE_URL_HISTORICO}
      PORT: 3002
      CORS_ORIGIN: http://localhost
      NODE_ENV: development
    restart: on-failure
    ports:
      - "3012:3002"
    networks:
      - cin_proxy

  frontend:
    build:
      context: ./frontend
    container_name: projeto-3-frontend
    volumes:
      - /opt/docker/frontends/projeto3:/output
    environment:
      NODE_ENV: production
    networks:
      - cin_proxy
    restart: "no"


volumes:
  register_modules:
  auth_modules:
  historico_modules:

networks:
  cin_proxy:
    external: true